[versions]
com-android-application = "8.2.0-alpha06"
org-jetbrains-kotlin-android = "1.8.0"
core-ktx = "1.9.0"
appcompat = "1.6.1"
material = "1.8.0"
recyclerview = "1.3.0"
constraintlayout = "2.1.4"
lifecycle-livedata-ktx = "2.6.1"
lifecycle-viewmodel-ktx = "2.6.1"
navigation-fragment-ktx = "2.5.3"
navigation-ui-ktx = "2.5.3"
legacy-support-v4 = "1.0.0"
preference = "1.2.0"
annotation = "1.6.0"
commons-io = "20030203.000550"
tinypinyin = "2.0.3"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle-livedata-ktx" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle-viewmodel-ktx" }
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation-fragment-ktx" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation-ui-ktx" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version = "4.11.0" }
gson = { group = "com.google.code.gson", name = "gson", version = "2.10.1" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version = "2.5.1" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version = "2.5.1" }
circleimageview = { group = "de.hdodenhof", name = "circleimageview", version = "3.1.0" }
glide = { group = "com.github.bumptech.glide", name = "glide", version = "4.15.1" }
bom = { group = "io.github.Rosemoe.sora-editor", name = "bom", version = "0.21.1" }
editor = { group = "io.github.Rosemoe.sora-editor", name = "editor", version = "0.21.1" }
language-textmate = { group = "io.github.Rosemoe.sora-editor", name = "language-textmate", version = "0.21.1" }
androidx-gridlayout = { group = "androidx.gridlayout", name = "gridlayout", version = "1.0.0" }
legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacy-support-v4" }
mmkv = { group = "com.tencent", name = "mmkv", version = "1.3.0" }
preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
jsoupxpath = { group = "cn.wanghaomiao", name = "JsoupXpath", version = "2.5.3" }
commons-compress = { group = "org.apache.commons", name = "commons-compress", version = "1.23.0" }
commons-io = { group = "commons-io", name = "commons-io", version.ref = "commons-io" }
tinypinyin = { group = "com.github.promeg", name = "tinypinyin", version.ref = "tinypinyin" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "com-android-application" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }

[bundles]
